services:
#  postgres:
#     image: postgres:13
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: CUSTOMPOA01
#       TZ: America/La_Paz
      
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"


  backend:
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    # healthcheck:
    #   test: ["CMD", "sh", "-c", "libreoffice --version"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    environment:
      DB_HOST: 10.0.10.224
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: Postgresql123
      DB_DATABASE: POA_DEV12
      TZ: America/La_Paz
     
    ports:
      - "3000:3000"
    # depends_on:
    #   - postgres

# volumes:
#   postgres_data: